server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;
  absolute_redirect off;

  location = /excalidraw {
    return 308 /excalidraw/;
  }

  location ^~ /excalidraw/api/files {
    rewrite ^/excalidraw(/api/files.*)$ $1 break;
    client_max_body_size 100m;
    proxy_pass http://excalidraw-api:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location ^~ /api/files {
    client_max_body_size 100m;
    proxy_pass http://excalidraw-api:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location ^~ /excalidraw/ {
    rewrite ^/excalidraw/(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
